version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
