version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra-data:/var/lib/cassandra

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-app
    depends_on:
      - redis
      - cassandra
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

volumes:
  cassandra-data:
