wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"

local urls = {
    "https://docs.python.org/3/",
    "https://fastapi.tiangolo.com/",
    "https://www.djangoproject.com/",
    "https://flask.palletsprojects.com/",
    "https://developer.mozilla.org/en-US/",
    "https://github.com/",
    "https://www.google.com/",
    "https://stackoverflow.com/",
    "https://realpython.com/",
    "https://www.postgresql.org/",
    "https://www.mysql.com/",
    "https://www.sqlite.org/",
    "https://www.mongodb.com/",
    "https://redis.io/",
    "https://kafka.apache.org/",
    "https://spark.apache.org/",
    "https://pandas.pydata.org/",
    "https://numpy.org/",
    "https://scikit-learn.org/",
    "https://huggingface.co/",
    "https://openai.com/",
    "https://platform.openai.com/",
    "https://www.tensorflow.org/",
    "https://pytorch.org/",
    "https://jupyter.org/",
    "https://matplotlib.org/",
    "https://seaborn.pydata.org/",
    "https://scipy.org/",
    "https://airflow.apache.org/",
    "https://superset.apache.org/",
    "https://aws.amazon.com/",
    "https://cloud.google.com/",
    "https://azure.microsoft.com/",
    "https://vercel.com/",
    "https://render.com/",
    "https://heroku.com/",
    "https://railway.app/",
    "https://netlify.com/",
    "https://bun.sh/",
    "https://nodejs.org/",
    "https://deno.com/",
    "https://vitejs.dev/",
    "https://nextjs.org/",
    "https://react.dev/",
    "https://vuejs.org/",
    "https://svelte.dev/",
    "https://astro.build/",
    "https://tailwindcss.com/",
    "https://getbootstrap.com/",
    "https://developer.chrome.com/",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "https://developer.mozilla.org/en-US/docs/Web/HTML",
    "https://wikipedia.org/",
    "https://linux.org/",
    "https://kernel.org/",
    "https://ubuntu.com/",
    "https://archlinux.org/",
    "https://debian.org/",
    "https://manjaro.org/",
    "https://pop.system76.com/",
    "https://www.gnu.org/",
    "https://www.linuxfoundation.org/",
    "https://www.gnu.org/software/bash/",
    "https://docs.docker.com/",
    "https://www.kubernetes.io/",
    "https://helm.sh/",
    "https://prometheus.io/",
    "https://grafana.com/",
    "https://www.terraform.io/",
    "https://www.ansible.com/",
    "https://www.jenkins.io/",
    "https://circleci.com/",
    "https://travis-ci.org/",
    "https://github.com/features/actions",
    "https://gitlab.com/",
    "https://bitbucket.org/",
    "https://gitea.io/",
    "https://about.gitlab.com/",
    "https://developer.hashicorp.com/",
    "https://datadog.com/",
    "https://sentry.io/",
    "https://logz.io/",
    "https://newrelic.com/",
    "https://rollbar.com/",
    "https://opentelemetry.io/",
    "https://nixos.org/",
    "https://guix.gnu.org/",
    "https://brew.sh/",
    "https://chocolatey.org/",
    "https://scoop.sh/",
    "https://www.pythonanywhere.com/",
    "https://replit.com/",
    "https://glitch.com/",
    "https://codepen.io/",
    "https://jsfiddle.net/",
    "https://codesandbox.io/",
    "https://developer.spotify.com/",
    "https://developer.twitter.com/",
    "https://developer.facebook.com/",
    "https://developers.google.com/",
    "https://console.cloud.google.com/"
}

-- Serialize Lua table to JSON array
function escape(s)
  return s:gsub('"', '\\"')
end

local function json_array(tbl)
  local str = "["
  for i, v in ipairs(tbl) do
    str = str .. '"' .. escape(v) .. '"'
    if i < #tbl then str = str .. "," end
  end
  return str .. "]"
end

wrk.body = json_array(urls)
